### ISSUE TITLE
POM breakage due to latest commit

### ISSUE THREAD

**Issue by turbomanage** [GoogleCloudPlatform/DataflowJavaSDK-examples#7]
SDK version 1.9.0 hasn't been pushed to maven central yet so commit 5a81bf1a7e376c4f07b52cae3ef708f0387fd939 breaks the build. Is there another repository where I can find dataflow-java-sdk in the mean time?

**Comment by davorbonaci** [comment]
As of last night, the Java SDK version 1.9.0 is available in the [Maven Central Repository](http://search.maven.org/#artifactdetails%7Ccom.google.cloud.dataflow%7Cgoogle-cloud-dataflow-java-sdk-all%7C1.9.0%7Cjar).

I'd suspect your environment tried to fetch the artifact from a mirror that didn't have the artifact propagated  yet, and subsequently cached that information.

Maven's `-U` option tells Maven to ignore cached information and to try to download the artifact despite the previous error. There's a decent chance that running `mvn -U clean verify` just once will fix your problem (`-U` should not be needed afterwards). If not, you may want to read details about Maven mirroring [here](http://maven.apache.org/guides/mini/guide-mirror-settings.html) and force usage of another server.

Finally, of course, you can wait just a little more; I'm pretty sure the problem will go away on its own. You can also checkout a previous commit that uses 1.8.1 SDK.

Hope this helps!

**Comment by turbomanage** [comment]
Thanks, Davor. I don't have a mirror configured and I've tried mvn -U but I
still get the same error. Despite the search page showing it's available,
the URL on the search page to browse the repo gives a 404:

http://repo1.maven.org/maven2/com/google/cloud/dataflow/google-cloud-dataflow-java-sdk-all/1.9.0/

**Comment by dhalperi** [comment]
hi @turbomanage,

Can you visit these URLs: 

* http://repo.maven.apache.org/maven2/com/google/cloud/dataflow/google-cloud-dataflow-java-sdk-all/1.9.0/google-cloud-dataflow-java-sdk-all-1.9.0.pom

* http://repo.maven.apache.org/maven2/com/google/cloud/dataflow/google-cloud-dataflow-java-sdk-all/1.9.0/google-cloud-dataflow-java-sdk-all-1.9.0.pom
* http://repo.maven.apache.org/maven2/com/google/cloud/dataflow/google-cloud-dataflow-java-sdk-all/1.9.0/google-cloud-dataflow-java-sdk-all-1.9.0.jar

These work for me locally, indicating that the Maven Central repository does have these jars even if the 1.9.0 link is not populating properly.

There may be some infrastructure issue (or caching delay) at Maven Central.

**Comment by turbomanage** [comment]
Those links work now, as does mvn -U for me locally :-) The 1.9.0 directory link at Maven Central still doesn't work, but I'll chalk it up to the MC caching gremlins and consider this resolved.

**Comment by dhalperi** [comment]
Thank you for the report and the resolution!
